application:
  ai:
    engine: ${AI_ENGINE:ollama}
    temperature: 0.6

    ollama:
      model: ${AI_MODEL:`qwen3:4b`}
      uri: http://localhost:11434
      force-augmentation: ${AI_AUGMENTER_ENABLED:true}
    openai:
      model: gpt-4o
      key: ${OPENAI_TOKEN:}
